#+title: Preguntas Frecuentes
#+date: 2021-06-04
#+draft: false
#+categories[]: anunciar
#+tags[]: rentar anuncios anuncio
#+layout: anunciar

* Cómo anunciarte
Para publicar un anuncio sólo necesitas [[https://chat.whatsapp.com/Dbuh9XTAkzh3PM25tVWAMv][unirte al grupo de WhatsApp]] y mandar la info con lo que
quieras que diga tu anuncio.

Puedes incluir todo tipo de contenido incluyendo texto, emojis, fotos, 
ubicación de tu negocio, links a tus redes sociales, etcétera.

No olvides incluir datos de contacto que serán visibles para que te busquen posibles
clientes.

Cada anuncio estará asociado a la cuenta de WhatsApp que nos contácte, y él propietario de ese
número de célular es el único que puede solicitar cambios de contenido o que se borre el anuncio.

* ¿Por qué existe ésta página?
Por qué a veces, los clientes no quieren recibir miles de mensages en un grupo de ventas, pero
quieren saber dónde buscarte cuando necesiten un plomero, una tienda de abarrotes, una escuela de idiomas, etc. 

** Quién puede anunciar
Negocios y servicios en Playa del Carmen, Quintana Roo, México. Nosotros sólo ofrecemos
el servicio de anuncio, las negociaciones y contrato final se hace directamente entre los
interesados.

** Tengo varios negocios
Anunciaremos todo lo que tú nos digas. Cada uno en su página con un link
partícular ¡GRATIS!

** Emojis  🥳👏🏘️
Los emojis son las caritas que aparecen por todo el internet.
También puedes incluirlas en tu anuncio. Búsca los que mejor
expresen tus ideas en [[https://emojipedia.org/][emojipedia]]

** Ya estoy anunciado en otro lugar
Aun así puedes anunciarte aquí, incluso puedes agregar links
a otras páginas como por ejemplo redes sociales.

** Mapa y gelocalización
Si deseas publicar la ubicación con ayuda de un mapa, sólo necesitamos
las coordenadas, si no sabes cómo conseguirlas, acércate
a nosotros.

** Quitar mi página
En cualquier momento puedes pedir que borremos la información que 
nos hayas proporcionado. Estar aquí es totalmente voluntario.

** No puedo
Si se te dificulta sólo pon toda la información como tú puedas y 
pide que lo acomodemos por ti. Sí aún te resulta demaciado difícil contáctanos
por WhatsApp [[https://wa.me/524522018336?text=xPlaya][452 201 8336]]
y con gusto te apoyamos.

** Sugerencias
Si tienes alguna duda o comentario, comunícate con nosotros 
por los canales arriba mencionados.

** Aviso de privacidad
La información que proporciones a éste sitio es totalmente tú responsabilidad.
Ten cuidado de no compartir datos que puedan poner en peligro tu integridad.
Si en cualquier momento sientes que necesitas modificar o borrar contenido, ponte
en contacto con nostros para apoyarte.

