#+title: Preguntas Frecuentes
#+date: 2021-06-04
#+draft: false
#+categories[]: anunciar
#+tags[]: rentar anuncios anuncio
#+layout: anunciar

* Cómo anunciarte
Para publicar un anuncio con nosotros sólo necesitas enviar un email con lo que
quieras que diga tu anuncio.

El email puede tener cualquier tipo de contenido incluyendo texto, emojis, fotos, video, 
coordenadas, links a otras páginas, etcétera.

Las imágenes pueden estar como archivos adjuntos. 

No olvides incluir datos de contacto que serán visibles para que te busquen posibles
clientes.

[[mailto:correo.rodrigo@gmail.com][correo.rodrigo@gmail.com]]

** Quién puede anunciar
Por ahora sólo estamos ofreciendo el servicio en México. Nosotros sólo ofrecemos
el servicio de anuncio, las negociaciones y contrato final se hace entre el 
propietario y el inquilino. Si te interesa éste servicio para otro país 
ponte en contacto con nostros.

** Tengo varias propiedades
Anunciaremos todas las que tu nos digas. Cada una en su página con un link
partícular ¡GRATIS!

** Emojis  🥳👏🏘️
Los emojis son las caritas que aparecen por todo el internet.
También puedes incluirlas en tu anuncio. Búsca los que mejor
expresen tus ideas en [[https://emojipedia.org/][emojipedia]]

** Ya estoy anunciado en otro lugar
Aun así puedes anunciarte aquí, incluso puedes agregar links
a otras páginas como por ejemplo redes sociales.

** Mi casa ya se rentó
Puedes pedir que se siga anunciando con la advertencia "rentada". O bien
puedes pedir que se deshabilite temporalmente tu anuncio y habilitarlo 
de nuevo cuando tu casa vuelva a estar disponible.

** Tarifas por temporada
Pon una tablita con las tarifas por temporada. Si no sabes cómo, nosotros te ayudamos.

** No quiero publicar el precio
Aunque se sugiere brindar toda la información disponible a los visitantes
de la página, nada es obligatorio, tú controlas tu contenido.

** Mapa y gelocalización
Si deseas publicar la ubicación con ayuda de un mapa, sólo necesitamos
las coordenadas, si no sabes cómo conseguirlas, acércate
a nosotros.

** Quitar mi página
En cualquier momento puedes pedir que borremos la información que 
nos hayas proporcionado. Estar aquí es totalmente voluntario.

** No puedo
Si se te dificulta sólo pon toda la información como tú puedas y 
pide que lo acomodemos por ti. Sí aún te resulta demaciado difícil contáctanos
por WhatsApp [[https://wa.me/524522018336?text=RENTAS][452 201 8336]]
y con gusto te apoyamos.

** Más servicios
Por ahora sólo ofrecemos rentas de bienes inmuebles, 
estamos explorando la posibilidad de extender éste modelo para
anunciar otros productos y servicios como: restaurantes, compra-venta
de vehículos, etcétera. Si algo de eso te parece
interesante hásnolo saber para iniciar cuanto antes.

** Sugerencias
Si tienes alguna duda o comentario, comunícate con nosotros 
por los canales arriba mencionados.

** Aviso de privacidad
La información que proporciones a éste sitio es totalmente tú responsabilidad.
Ten cuidado de no compartir datos que puedan poner en peligro tu integridad.
Si en cualquier momento sientes que necesitas modificar o borrar contenido, ponte
en contacto con nostros para apoyarte.

