#+title: La Huerta Casa de Campo
#+date: 2021-06-04
#+draft: false
#+categories[]: casa
#+tags[]: campo fiestas salon

Se renta casa en zona boscosa de Uruapan, ideal para familias
grandes que vienen de vacaciones o fiestas de fin de semana.

Cuenta con dos camas individuales y una matrimonial. Las cuales se 
pueden organizar o remover de acuerdo a sus necesidades. 
Ba침o pr칤ncipal incluye tina de hidromasage. 

* Caracter칤sticas
- Ba침o pr칤cipal con regadera y tina de hidromasage
- Ba침o secundario con regadera
- 2 Habitaciones grandes
- Cocina equipada
- Comedor de 8 puestos
- Barra/Desayunador de 6 puestos
- 츼rea exterior de fogatas
- Sala con chimenea

* Cocina
Refrigerador, estufa con horno de gas, licuadora, horno de micro ondas, 
barra para 6 personas, utensilios b치sicos

* Horno de barro
 Quieres horenear pan, pizza, hacer una carne asada con tus amigos... 

* Detalles
La propiedad cuenta con una hect치rea de terreno a tu disposici칩n,
espacio para que jueguen tus hijos y se divierta toda la familia. 
Estacionamiento para todos tus autos y los de tus amigos. 

* Informes y reservaciones
Casa la Huerta游님452 201 8336 
https://rogithub.github.io/la-huerta/